services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/app/static  
      - media:/media    
    env_file: 
      - .env
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 30 --max-requests 1000 --log-level info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static 
      - media:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
    networks:
      - app_network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: 
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

volumes:
  static:
  media:
  mysql_data:

networks:
  app_network:
