services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/app/static
    env_file: 
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - app_network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: 
      - .env
    networks:
      - app_network

volumes:
  static:
  mysql_data:

networks:
  app_network:
