# Generated by Django 5.1.5 on 2025-01-29 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('número', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('país', models.CharField(default='Brasil', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia_da_empresa', models.CharField(max_length=254)),
                ('número_de_telefone_da_empresa', models.CharField(max_length=15)),
                ('cnpj_da_empresa', models.CharField(max_length=12)),
                ('data_de_registro_da_empresa', models.DateTimeField(editable=False)),
                ('última_edição_no_perfil_da_empresa', models.DateTimeField(editable=False)),
                ('endereço_da_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='customers.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_representante_legal', models.CharField(max_length=254)),
                ('cpf_do_representante_legal', models.CharField(max_length=11)),
                ('cargo_do_representante_legal', models.CharField(max_length=254)),
                ('email_do_representante_legal', models.EmailField(max_length=254)),
                ('data_de_registro_do_representante', models.DateTimeField(editable=False)),
                ('última_edição_no_perfil_do_representante', models.DateTimeField(editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='customers.empresa')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
