# Generated by Django 5.0.4 on 2024-08-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia_da_empresa', models.CharField(max_length=254)),
                ('endereço_da_empresa', models.CharField(max_length=254)),
                ('número_de_telefone_da_empresa', models.CharField(max_length=15)),
                ('data_de_registro_da_empresa', models.DateTimeField(editable=False)),
                ('última_edição_no_perfil_da_empresa', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_representante_legal', models.CharField(max_length=254)),
                ('rg_do_representante_legal', models.CharField(max_length=9)),
                ('cpf_do_representante_legal', models.CharField(max_length=11)),
                ('cargo_do_representante_legal', models.CharField(max_length=254)),
                ('email_do_representante_legal', models.EmailField(max_length=254)),
                ('data_de_registro_do_representante', models.DateTimeField(editable=False)),
                ('última_edição_no_perfil_do_representante', models.DateTimeField(editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='customers.empresa')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
