# Generated by Django 5.0.4 on 2025-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='rg_do_representante_legal',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj_da_empresa',
            field=models.CharField(default='000000000000', max_length=12),
            preserve_default=False,
        ),
    ]
