# Generated by Django 5.0.4 on 2024-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_representante_legal', models.CharField(max_length=254)),
                ('rg_do_representante_legal', models.CharField(max_length=9)),
                ('cpf_do_representante_legal', models.CharField(max_length=11)),
                ('cargo_do_representante_legal', models.CharField(max_length=254)),
                ('nome_fantasia_da_empresa', models.CharField(max_length=254)),
                ('endereco_da_empresa', models.CharField(max_length=254)),
                ('numero_de_telefone_da_empresa', models.CharField(max_length=15)),
                ('email_da_empresa', models.EmailField(max_length=254)),
                ('data_de_registro_da_empresa', models.DateTimeField(editable=False)),
                ('ultima_edicao_perfil_da_empresa', models.DateTimeField()),
            ],
        ),
    ]
