# Generated by Django 5.0.4 on 2024-05-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cliente'),
        ('files', '0002_arquivo_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
