# Generated by Django 5.1.5 on 2025-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
