# Generated by Django 5.0.4 on 2025-01-28 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_representante_rg_do_representante_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('número', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('país', models.CharField(default='Brasil', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereço_da_empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='customers.endereço'),
        ),
    ]
