# Generated by Django 5.0.4 on 2024-05-21 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco_da_empresa',
            new_name='endereço_da_empresa',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_de_telefone_da_empresa',
            new_name='número_de_telefone_da_empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ultima_edicao_perfil_da_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='última_edição_no_perfil_da_empresa',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
