# Generated by Django 5.0.4 on 2025-01-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_endereco_alter_empresa_endereco_da_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereço',
            new_name='Endereco',
        ),
    ]
