# Generated by Django 5.0.4 on 2024-05-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_endereco_da_empresa_cliente_endereço_da_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuário_da_empresa',
            field=models.CharField(default=None, max_length=254, null=True),
        ),
    ]
