# Generated by Django 5.0.4 on 2024-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_cliente_usuário_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuário_da_empresa',
            field=models.CharField(default='teste', max_length=254),
            preserve_default=False,
        ),
    ]
