# Generated by Django 5.0.4 on 2024-06-10 05:37

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_cliente_usuário_da_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuário_da_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuários_da_empresa',
            field=models.JSONField(default=list),
            preserve_default=False,
        ),
    ]
