# Generated by Django 5.0.4 on 2024-06-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_empresa_representante'),
        ('files', '0004_alter_arquivo_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='representante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.empresa'),
        ),
    ]
