# Generated by Django 5.0.4 on 2024-06-17 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_representante_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuários_associados',
        ),
        migrations.AlterField(
            model_name='representante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='customers.empresa'),
        ),
    ]
