# Generated by Django 5.0.4 on 2024-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_empresa_usuários_associados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email_da_empresa',
        ),
        migrations.AddField(
            model_name='representante',
            name='email_do_representante_legal',
            field=models.EmailField(default='vinicius_loureiro_cavalcante@hotmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
