# Generated by Django 5.0.4 on 2024-05-08 17:04

import django.db.models.deletion
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_description', models.TextField(blank=True)),
                ('file_path', models.FileField(upload_to=files.models.file_upload_path)),
                ('file_uploaded_at', models.DateTimeField(editable=False)),
                ('file_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
