# Generated by Django 5.0.4 on 2024-08-15 23:38

import django.db.models.deletion
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_arquivo', models.CharField(max_length=255)),
                ('descrição_do_arquivo', models.TextField(blank=True)),
                ('endereço_do_arquivo', models.FileField(upload_to=files.models.file_upload_path)),
                ('data_de_upload_do_arquivo', models.DateTimeField(editable=False)),
                ('ano_do_arquivo', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customers.empresa')),
            ],
        ),
    ]
