# Generated by Django 5.0.4 on 2025-01-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='validade_do_arquivo',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
