# Generated by Django 5.0.4 on 2024-05-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_arquivo_delete_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo',
            old_name='descricao_do_arquivo',
            new_name='descrição_do_arquivo',
        ),
        migrations.RenameField(
            model_name='arquivo',
            old_name='endereco_do_arquivo',
            new_name='endereço_do_arquivo',
        ),
    ]
