# Generated by Django 5.0.4 on 2024-06-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_empresa_representante'),
        ('files', '0003_rename_descricao_do_arquivo_arquivo_descrição_do_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.empresa'),
        ),
    ]
