# Generated by Django 5.0.4 on 2024-06-17 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_empresa_usuários_associados_and_more'),
        ('files', '0004_alter_arquivo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='ano_do_arquivo',
            field=models.CharField(default='2024', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customers.empresa'),
        ),
    ]
